# Generated by Django 5.1.3 on 2024-11-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='item_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
