# Generated by Django 5.1.3 on 2024-11-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_menuitems_item_of_the_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='item_of_the_day',
        ),
    ]
